on: [push, pull_request]

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  msvc:
    name: MSVC
    strategy:
      fail-fast: false
      matrix:
        rust_version: [stable, 1.76.0]
        target:
          - x86_64-pc-windows-msvc
          - i686-pc-windows-msvc
          - aarch64-pc-windows-msvc

    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust_version }}
          targets: ${{ matrix.target }}

      - run: pip install "pefile==2024.8.26"
      - run: cargo build --verbose --release --target ${{ matrix.target }} --workspace

      - if: contains(matrix.target, '86')
        run: cd .. && rm rust-embed-resource && git clone https://github.com/chawyehsu/embed-resource-issue-90-vswhom-cross rust-embed-resource
      - if: contains(matrix.target, '86')
        uses: prefix-dev/setup-pixi@v0.9.5
      #  with:
      #    pixi-version: v0.66.0
      - if: contains(matrix.target, '86')
        run: pixi run build --target-platform win-arm64
